energy.base-url=${HOME_AUTOMATION_ENEDIS_BASE_URL:https://gw.ext.prod-sandbox.api.enedis.fr}
energy.client-id=${HOME_AUTOMATION_ENEDIS_CLIENT_ID:replace-with-client-id}
energy.secret=${HOME_AUTOMATION_ENEDIS_SECRET:replace-with-secret}
energy.oauth-path=${HOME_AUTOMATION_ENEDIS_OAUTH_PATH:/oauth2/v3/token}
energy.duration=${HOME_AUTOMATION_ENEDIS_DURATION:PT12M}
server.port=${HOME_AUTOMATION_ENEDIS_SERVER_PORT:8085}
springdoc.swagger-ui.url=/v3/api-docs
springdoc.server-url=${SPRINGDOC_SERVER_URL:http://localhost:8085}
